<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GameMode</title>
</head>
<body>
    <h1>Empresa GameMode</h1>
    <?php 
        echo "<h2> Bem vindo a nossa página! </h2>";
        echo "<p> Somos uma empresa de jogos </p>";
        echo "<p> Veja alguns jogos que temos disponiveis! </p>";

        echo "<img src= https://i.metroimg.com/vvfQBh6ezgtWELGOmVsNgny31-jhRFsvQkgXNWgp28c/w:900/q:85/f:webp/plain/https://images.metroimg.com/2025/10/22141057/jogos-5.jpg>"

        // Aqui é eu comentando
        # Aqui também! 
        /* E aqui também! :D */
    ?>
</body>
</html>